services:
  client:
    stdin_open: true
    tty: true
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./client
        target: /app
      - type: volume
        target: /app/node_modules
    ports:
      - "8080:5173"
    restart: unless-stopped
    depends_on:
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      PORT: 80
      DB_URL: mongodb://${MONGODB_ROOT_USERNAME}:${MONGODB_ROOT_PASSWORD}@db/${MONGODB_DATABASE}
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./server/src
        target: /app/src
    ports:
      - "3000:80"
    restart: unless-stopped
  db:
   container_name: note-taker-db
   image: mongo:latest
   restart: always
   environment:
     MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
     MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
     MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
   ports:
     - "27017:27017"
   volumes:
     - mongodb_data:/data/db

volumes:
  mongodb_data:
    name: note-taker-data
    external: true